version: '3'
services:
  db:
    image: postgres
    container_name: pdm_db
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: containers/web
    container_name: pdm_web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/www
      - bundle_volume:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle_volume:
