version: 2.1
orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7-node
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: pdm_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: password
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages
  - run:
      name: DB の待機
      command: dockerize -wait tcp://localhost:5432 -timeout 1m
  - run:
      name: データベースのセットアップ
      command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
