version: 2.1
orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7-node
        environment:
          RAILS_ENV: test
          DATABASE_HOST: 127.0.0.1
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: pdm_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: "bundle install"
          command: bundle install --path vendor/bundle
      # DBと接続できるまで待機
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: "initialize DB"
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      #- run:
          #name: RSpec
          #command: bundle exec rspec
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
