# https://circleci.com/developer/ja/orbs/orb/circleci/ruby

version: 2.1

# https://circleci.com/docs/ja/orb-intro/
# https://circleci.com/developer/ja/orbs
orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2-node
    steps:
      - checkout
      - ruby/install-deps
      # - node/install-packages:
      - run: echo "Hello, CircleCI"
workflows:
  build_and_test:
    jobs:
      - build
