version: 2.1
orbs:
  node: circleci/node@5.0.2
  ruby: circleci/ruby@1.8.0
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2-node
    steps:
      - checkout
      - run: echo "hello circle ci"
workflows:
  build_and_test:
    jobs:
      - build